import { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";

function SB({ s }) { const st = { uploaded: "bg-blue-500/15 text-blue-400 border border-blue-500/30", under_review: "bg-amber-500/15 text-amber-400 border border-amber-500/30", approved: "bg-emerald-500/15 text-emerald-400 border border-emerald-500/30", rejected: "bg-red-500/15 text-red-400 border border-red-500/30", expired: "bg-rose-500/15 text-rose-400 border border-rose-500/30" }; return <span className={`inline-flex items-center px-2.5 py-0.5 rounded-md text-xs font-medium ${st[s] || st.uploaded}`}>{s?.replace("_", " ")}</span>; }

export default function Documents() {
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(""); const [statusFilter, setStatusFilter] = useState("all"); const [typeFilter, setTypeFilter] = useState("all");
  useEffect(() => { load(); }, []);
  async function load() { setLoading(true); const { data } = await supabase.from("documents").select("*").order("created_at", { ascending: false }); setItems(data || []); setLoading(false); }
  async function updateStatus(id, status) { await supabase.from("documents").update({ status, reviewed_at: new Date().toISOString() }).eq("id", id); load(); }
  const filtered = useMemo(() => items.filter(d => { if (statusFilter !== "all" && d.status !== statusFilter) return false; if (typeFilter !== "all" && d.document_type !== typeFilter) return false; const q = search.toLowerCase(); return !q || (d.document_name || "").toLowerCase().includes(q); }), [items, search, statusFilter, typeFilter]);
  const counts = useMemo(() => { const c = { all: items.length, uploaded: 0, under_review: 0, approved: 0, rejected: 0, expired: 0 }; items.forEach(d => { if (c[d.status] !== undefined) c[d.status]++; }); return c; }, [items]);
  const ownerLabel = (t, id) => { const l = { driver: `Driver #${id}`, vehicle: `Vehicle #${id}`, fleet_owner: `Fleet #${id}`, route: `Route #${id}`, customer: `Customer #${id}` }; return l[t] || `${t} #${id}`; };

  return (
    <div className="max-w-6xl">
      <div className="mb-4"><h1 className="text-2xl font-bold text-white">Documents</h1><p className="text-sm text-slate-400">Manage compliance documents</p></div>
      <div className="bg-slate-800/50 rounded-2xl border border-slate-700/50 p-1 mb-4"><div className="flex gap-1 flex-wrap">{["all","uploaded","under_review","approved","rejected","expired"].map(s => (<button key={s} onClick={() => setStatusFilter(s)} className={`px-3 py-1.5 rounded-xl text-xs font-medium capitalize transition ${statusFilter === s ? "bg-slate-700 text-white" : "text-slate-400 hover:text-white hover:bg-slate-700/50"}`}>{s.replace("_", " ")} <span className="ml-1 text-slate-500">{counts[s] || 0}</span></button>))}</div></div>
      <div className="flex gap-3 mb-4"><input type="text" placeholder="Search documents..." value={search} onChange={e => setSearch(e.target.value)} className="flex-1 bg-slate-800/50 border border-slate-700/50 rounded-xl px-4 py-2.5 text-sm text-white placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-cyan-500/50" /><select value={typeFilter} onChange={e => setTypeFilter(e.target.value)} className="bg-slate-800/50 border border-slate-700/50 rounded-xl px-3 py-2.5 text-sm text-white"><option value="all">All Types</option><option value="license">License</option><option value="insurance">Insurance</option><option value="vehicle_inspection">Inspection</option><option value="registration">Registration</option></select></div>
      {loading ? <div className="text-center py-12 text-slate-400">Loading...</div> : filtered.length === 0 ? <div className="bg-slate-800/50 rounded-2xl border border-slate-700/50 p-12 text-center"><p className="text-slate-400">No documents</p></div> : (
        <div className="bg-slate-800/50 rounded-2xl border border-slate-700/50 overflow-hidden"><div className="overflow-x-auto"><table className="w-full"><thead><tr className="border-b border-slate-700/50"><th className="text-left text-xs font-semibold text-slate-400 uppercase px-4 py-3">Document</th><th className="text-left text-xs font-semibold text-slate-400 uppercase px-4 py-3">Type</th><th className="text-left text-xs font-semibold text-slate-400 uppercase px-4 py-3">Owner</th><th className="text-left text-xs font-semibold text-slate-400 uppercase px-4 py-3">Expiry</th><th className="text-left text-xs font-semibold text-slate-400 uppercase px-4 py-3">Status</th><th className="text-right text-xs font-semibold text-slate-400 uppercase px-4 py-3">Actions</th></tr></thead><tbody className="divide-y divide-slate-700/30">
          {filtered.map(doc => (<tr key={doc.id} className="hover:bg-slate-700/20 transition"><td className="px-4 py-3"><div className="flex items-center gap-3"><div className="w-8 h-8 rounded-lg bg-cyan-500/20 flex items-center justify-center text-xs text-cyan-400 font-bold">D</div><div><p className="text-sm text-white font-medium">{doc.document_name}</p></div></div></td><td className="px-4 py-3 text-sm text-slate-300 capitalize">{doc.document_type?.replace("_", " ")}</td><td className="px-4 py-3 text-sm text-slate-300">{ownerLabel(doc.owner_type, doc.owner_id)}</td><td className="px-4 py-3 text-sm text-slate-300">{doc.expiry_date ? new Date(doc.expiry_date).toLocaleDateString() : "—"}</td><td className="px-4 py-3"><SB s={doc.status} /></td><td className="px-4 py-3 text-right"><div className="flex items-center justify-end gap-1">{doc.status === "uploaded" && (<><button onClick={() => updateStatus(doc.id, "approved")} className="text-xs bg-emerald-500/20 text-emerald-400 px-2 py-1 rounded">Approve</button><button onClick={() => updateStatus(doc.id, "rejected")} className="text-xs bg-red-500/20 text-red-400 px-2 py-1 rounded">Reject</button></>)}{doc.file_url && <a href={doc.file_url} target="_blank" rel="noopener noreferrer" className="text-xs bg-blue-500/20 text-blue-400 px-2 py-1 rounded">View</a>}</div></td></tr>))}
        </tbody></table></div></div>
      )}
    </div>
  );
}
