import { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";

function SB({ s }) { const st = { open: "bg-yellow-500/15 text-yellow-400 border border-yellow-500/30", in_progress: "bg-cyan-500/15 text-cyan-400 border border-cyan-500/30", on_hold: "bg-amber-500/15 text-amber-400 border border-amber-500/30", completed: "bg-emerald-500/15 text-emerald-400 border border-emerald-500/30", cancelled: "bg-red-500/15 text-red-400 border border-red-500/30" }; return <span className={`inline-flex items-center px-2.5 py-0.5 rounded-md text-xs font-medium ${st[s] || st.open}`}>{s?.replace("_", " ")}</span>; }
function PB({ p }) { const st = { low: "bg-slate-500/15 text-slate-400 border border-slate-500/30", medium: "bg-blue-500/15 text-blue-400 border border-blue-500/30", high: "bg-orange-500/15 text-orange-400 border border-orange-500/30", urgent: "bg-red-500/15 text-red-400 border border-red-500/30" }; return <span className={`inline-flex items-center px-2 py-0.5 rounded text-xs font-medium ${st[p] || st.medium}`}>{p}</span>; }

export default function WorkItems() {
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(""); const [filter, setFilter] = useState("all");
  useEffect(() => { load(); }, []);
  async function load() { setLoading(true); const { data } = await supabase.from("work_items").select("*").order("created_at", { ascending: false }); setItems(data || []); setLoading(false); }
  async function updateStatus(id, status) { const up = { status }; if (status === "completed") up.completed_at = new Date().toISOString(); await supabase.from("work_items").update(up).eq("id", id); load(); }
  const filtered = useMemo(() => items.filter(w => { if (filter !== "all" && w.status !== filter) return false; const q = search.toLowerCase(); return !q || (w.title || "").toLowerCase().includes(q); }), [items, search, filter]);
  const counts = useMemo(() => { const c = { all: items.length, open: 0, in_progress: 0, on_hold: 0, completed: 0, cancelled: 0 }; items.forEach(w => { if (c[w.status] !== undefined) c[w.status]++; }); return c; }, [items]);
  const entityLabel = (t, id) => { const l = { booking: `Booking #${id}`, subscription: `Subscription #${id}`, fleet_owner: `Fleet #${id}`, driver: `Driver #${id}`, vehicle: `Vehicle #${id}`, route: `Route #${id}`, customer: `Customer #${id}`, invoice: `Invoice #${id}` }; return l[t] || `${t} #${id}`; };

  return (
    <div className="max-w-6xl">
      <div className="mb-4"><h1 className="text-2xl font-bold text-white">Work Items</h1><p className="text-sm text-slate-400">Track tasks and issues across entities</p></div>
      <div className="bg-slate-800/50 rounded-2xl border border-slate-700/50 p-1 mb-4"><div className="flex gap-1 flex-wrap">{["all","open","in_progress","on_hold","completed"].map(s => (<button key={s} onClick={() => setFilter(s)} className={`px-3 py-1.5 rounded-xl text-xs font-medium capitalize transition ${filter === s ? "bg-slate-700 text-white" : "text-slate-400 hover:text-white hover:bg-slate-700/50"}`}>{s.replace("_", " ")} <span className="ml-1 text-slate-500">{counts[s] || 0}</span></button>))}</div></div>
      <input type="text" placeholder="Search tasks..." value={search} onChange={e => setSearch(e.target.value)} className="w-full bg-slate-800/50 border border-slate-700/50 rounded-xl px-4 py-2.5 text-sm text-white placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-cyan-500/50 mb-4" />
      {loading ? <div className="text-center py-12 text-slate-400">Loading...</div> : filtered.length === 0 ? <div className="bg-slate-800/50 rounded-2xl border border-slate-700/50 p-12 text-center"><p className="text-slate-400">No work items</p></div> : (
        <div className="bg-slate-800/50 rounded-2xl border border-slate-700/50 overflow-hidden"><div className="overflow-x-auto"><table className="w-full"><thead><tr className="border-b border-slate-700/50"><th className="text-left text-xs font-semibold text-slate-400 uppercase px-4 py-3">Task</th><th className="text-left text-xs font-semibold text-slate-400 uppercase px-4 py-3">Priority</th><th className="text-left text-xs font-semibold text-slate-400 uppercase px-4 py-3">Assigned</th><th className="text-left text-xs font-semibold text-slate-400 uppercase px-4 py-3">Entity</th><th className="text-left text-xs font-semibold text-slate-400 uppercase px-4 py-3">Due</th><th className="text-left text-xs font-semibold text-slate-400 uppercase px-4 py-3">Status</th><th className="text-right text-xs font-semibold text-slate-400 uppercase px-4 py-3">Actions</th></tr></thead><tbody className="divide-y divide-slate-700/30">
          {filtered.map(w => (<tr key={w.id} className="hover:bg-slate-700/20 transition"><td className="px-4 py-3"><p className="text-sm text-white font-medium">{w.title}</p><p className="text-xs text-slate-500">{w.description?.slice(0, 60)}...</p></td><td className="px-4 py-3"><PB p={w.priority} /></td><td className="px-4 py-3 text-sm text-slate-300">{w.assigned_to || "—"}</td><td className="px-4 py-3 text-sm text-slate-300">{w.entity_type ? entityLabel(w.entity_type, w.entity_id) : "—"}</td><td className="px-4 py-3 text-sm text-slate-300">{w.due_date ? new Date(w.due_date).toLocaleDateString() : "—"}</td><td className="px-4 py-3"><SB s={w.status} /></td><td className="px-4 py-3 text-right"><div className="flex items-center justify-end gap-1">{w.status === "open" && <button onClick={() => updateStatus(w.id, "in_progress")} className="text-xs bg-cyan-500/20 text-cyan-400 px-2 py-1 rounded">Start</button>}{w.status === "in_progress" && <button onClick={() => updateStatus(w.id, "completed")} className="text-xs bg-emerald-500/20 text-emerald-400 px-2 py-1 rounded">Complete</button>}{(w.status === "open" || w.status === "in_progress") && <button onClick={() => updateStatus(w.id, "on_hold")} className="text-xs bg-amber-500/20 text-amber-400 px-2 py-1 rounded">Hold</button>}</div></td></tr>))}
        </tbody></table></div></div>
      )}
    </div>
  );
}
